#!/usr/bin/env bash
# =============================================================================
# K-talysticFlow (KAST) — Setup Script [Linux / macOS / WSL]
# =============================================================================
# USAGE:
#   bash setup.sh              → Install
#   bash setup.sh --update     → Update existing env
#   bash setup.sh --uninstall  → Remove env + shortcuts
#   bash setup.sh --help       → Show help
# =============================================================================

set -euo pipefail

ENV_NAME="ktalysticflow"
BIN_DIR="$HOME/.local/bin"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WRAPPER_SCRIPT="$BIN_DIR/kast"
DESKTOP_DIR="$HOME/.local/share/applications"
ICON_PATH="$SCRIPT_DIR/docs/_static/kast_logo.png"

# Color codes
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

TOTAL_STEPS=5

banner() {
  echo -e "\n${CYAN}${BOLD}╔════════════════════════════════════════╗${RESET}"
  echo -e "${CYAN}${BOLD}║  K-talysticFlow (KAST) — Setup        ║${RESET}"
  echo -e "${CYAN}${BOLD}╚════════════════════════════════════════╝${RESET}"
  echo -e "\n  OS      : $(uname -s)"
  echo -e "  Project : $SCRIPT_DIR\n"
}

step()   { echo -e "\n${BOLD}► [$1/$TOTAL_STEPS] $2${RESET}"; }
ok()     { echo -e "  ${GREEN}✅ $1${RESET}"; }
warn()   { echo -e "  ${YELLOW}⚠️  $1${RESET}"; }

show_usage() {
    echo -e "${CYAN}${BOLD}KAST Setup Script${RESET}"
    echo ""
    echo "Usage: $0 [OPTION]"
    echo ""
    echo "Options:"
    echo "  (default)      Create a new environment"
    echo "  --update       Update existing environment"
    echo "  --uninstall    Remove the environment and shortcuts"
    echo "  --help         Show this help message"
}

# Check if conda is installed
check_conda() {
    if ! command -v conda &> /dev/null; then
        echo -e "${RED}❌ Conda not found!${RESET}"
        echo "Please install Conda: https://docs.conda.io/projects/conda/en/latest/user-guide/install/linux.html"
        exit 1
    fi
    ok "Conda found: $(conda --version)"
}

# Check if environment exists
check_env_exists() {
    conda env list | grep -q "^${ENV_NAME} "
}

setup_environment() {
    local action=$1 # "create" or "update"
    
    if [ "$action" = "create" ]; then
        echo "yes" | conda env create -f "$SCRIPT_DIR/environment.yml"
    else
        echo "yes" | conda env update -f "$SCRIPT_DIR/environment.yml" --prune
    fi
    
    if [ $? -eq 0 ]; then
        ok "Environment ${action}d successfully"
    else
        echo -e "${RED}❌ Failed to ${action} environment${RESET}"
        exit 1
    fi
}

# Get conda path
get_conda_path() {
    CONDA_INFO=$(conda info --json)
    echo "$CONDA_INFO" | grep -o '"conda_prefix": "[^"]*' | head -1 | sed 's/"conda_prefix": "//' || echo ""
}

# Create wrapper script to run conda without activation
create_wrapper_script() {
    echo -e "${YELLOW}📝 Creating CLI command...${RESET}"
    
    mkdir -p "$BIN_DIR"
    local conda_base
    conda_base="$(conda info --base)"
    
    cat > "$WRAPPER_SCRIPT" << EOF
#!/usr/bin/env bash
# KAST CLI launcher — auto-generated by setup.sh
source "${conda_base}/etc/profile.d/conda.sh"
conda activate "${ENV_NAME}"

# Fix libstdc++ compatibility (safe on all Linux systems)
export LD_LIBRARY_PATH="\$CONDA_PREFIX/lib:\$LD_LIBRARY_PATH"

# Suppress TensorFlow/XLA CUDA warnings (CPU-only setup)
export TF_CPP_MIN_LOG_LEVEL=2
export XLA_FLAGS="--xla_force_host_platform_device_count=1"

cd "${SCRIPT_DIR}"
python main.py "\$@"
EOF
    
    chmod +x "$WRAPPER_SCRIPT"
    
    # Add ~/.local/bin to PATH if needed
    for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
        if [ -f "$rc" ] && ! grep -q '/.local/bin' "$rc"; then
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$rc"
            warn "Added ~/.local/bin to PATH in $rc — restart terminal"
        fi
    done
    
    export PATH="$BIN_DIR:$PATH"
    ok "CLI command 'kast' created $(echo "→ type 'kast' from anywhere")"
}

# Create desktop shortcut
create_desktop_shortcut() {
    mkdir -p "$DESKTOP_DIR"
    
    local shortcut_file="$DESKTOP_DIR/kast.desktop"
    local icon_line="Icon=$ICON_PATH"
    
    if [ ! -f "$ICON_PATH" ]; then
        icon_line="Icon=application-science"
        warn "Icon not found, using system fallback"
    fi
    
    cat > "$shortcut_file" << DESKTOP_EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=K-talysticFlow
GenericName=Molecular Activity Predictor
Comment=Deep Learning pipeline for molecular prediction (KAST)
Exec=$WRAPPER_SCRIPT
${icon_line}
Terminal=true
StartupNotify=true
Categories=Science;Chemistry;Development;
Path=$SCRIPT_DIR
DESKTOP_EOF

    chmod +x "$shortcut_file"
    command -v update-desktop-database &>/dev/null && \
        update-desktop-database "$DESKTOP_DIR" 2>/dev/null || true
    
    ok "Desktop shortcut created"
}

# Create all shortcuts and CLI
create_shortcuts() {
    echo ""
    echo -e "${YELLOW}🔗 Creating shortcuts and CLI command...${RESET}"
    create_wrapper_script
    create_desktop_shortcut
}

# Uninstall environment and remove shortcuts
uninstall() {
    echo ""
    read -p "Are you sure you want to uninstall KAST? (yes/NO) " -r
    echo
    if [[ $REPLY =~ ^[Yy][Ee][Ss]$ ]]; then
        echo -e "${YELLOW}🗑️  Removing...${RESET}"
        source "$(conda info --base)/etc/profile.d/conda.sh" 2>/dev/null || true
        conda remove -n "$ENV_NAME" --all -y 2>/dev/null && ok "Conda env removed" || warn "Env not found"
        rm -f "$WRAPPER_SCRIPT" && ok "CLI removed" || warn "CLI not found"
        rm -f "$DESKTOP_DIR/kast.desktop" && ok "Desktop entry removed" || warn "Entry not found"
        echo -e "\n${GREEN}Uninstall complete.${RESET}"
    else
        echo "Cancelled."
    fi
    exit 0
}

# Validate installation
validate_install() {
    echo ""
    step 5 "Validating installation..."
    
    if conda run -n "$ENV_NAME" python bin/check_env.py 2>/dev/null; then
        ok "All dependencies validated"
    else
        warn "Some packages may be missing — run: conda activate $ENV_NAME && python bin/check_env.py"
    fi
}

# Main script
main() {
    banner
    
    local action="install"
    [ $# -gt 0 ] && action="$1"
    
    case "$action" in
        --help|-h)
            show_usage
            exit 0
            ;;
        --uninstall)
            uninstall
            ;;
        --update)
            step 1 "Checking conda..."
            check_conda
            source "$(conda info --base)/etc/profile.d/conda.sh"
            
            if ! conda info --envs | grep -q "^$ENV_NAME "; then
                echo -e "${RED}❌ Environment '$ENV_NAME' not found!${RESET}"
                exit 1
            fi
            
            step 2 "Updating environment..."
            setup_environment "update"
            
            step 3 "Creating CLI command..."
            create_wrapper_script
            
            step 4 "Creating desktop shortcut..."
            create_desktop_shortcut
            
            validate_install
            ;;
        *)
            # Default: install
            step 1 "Checking conda..."
            check_conda
            source "$(conda info --base)/etc/profile.d/conda.sh"
            
            step 2 "Setting up environment..."
            if conda info --envs | grep -q "^$ENV_NAME "; then
                echo -e "${YELLOW}⚠️  Environment '$ENV_NAME' exists!${RESET}"
                read -p "Update it instead? (yes/NO) " -r
                echo
                if [[ $REPLY =~ ^[Yy][Ee][Ss]$ ]]; then
                    setup_environment "update"
                else
                    ok "Keeping existing environment"
                fi
            else
                setup_environment "create"
            fi
            
            step 3 "Creating CLI and shortcuts..."
            create_shortcuts
            
            step 4 "Validating..."
            validate_install
            ;;
    esac
    
    echo ""
    echo -e "${CYAN}${BOLD}════════════════════════════════════════${RESET}"
    echo -e "${GREEN}${BOLD}✅  Setup Complete!${RESET}"
    echo -e "${CYAN}${BOLD}════════════════════════════════════════${RESET}"
    echo ""
    echo -e "  ${BOLD}How to run KAST:${RESET}"
    echo -e "    Terminal  →  ${CYAN}kast${RESET}  (from any terminal)"
    echo -e "    Direct    →  ${CYAN}conda activate $ENV_NAME && python main.py${RESET}"
    echo -e "    Desktop   →  search 'K-talysticFlow' in app menu"
    echo ""
    echo -e "  ${BOLD}Other commands:${RESET}"
    echo -e "    Verify env  →  ${CYAN}conda activate $ENV_NAME && python bin/check_env.py${RESET}"
    echo -e "    Update      →  ${CYAN}bash setup.sh --update${RESET}"
    echo -e "    Uninstall   →  ${CYAN}bash setup.sh --uninstall${RESET}"
    echo ""
}

main "$@"
